name: Docker CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build test image
        run: |
          docker build -t my-fastapi-app:test .

      - name: Create CI environment file
        run: |
          cat <<EOF > .env
          DB_HOST=db
          DB_USER=root
          DB_PASSWORD=root123
          DB_NAME=company
          MYSQL_ROOT_PASSWORD=root123
          MYSQL_DATABASE=company
          EOF

      - name: Start application stack
        run: |
          docker compose up -d --build

      - name: Wait for services
        run: |
          for i in {1..12}; do
            if curl -f http://localhost:8000/health; then
              echo "API is healthy"
              exit 0
            fi

            echo "Waiting for API..."
            sleep 5
          done

          echo "API health check failed"
          docker compose logs
          exit 1

      - name: Test employees endpoint
        run: |
          curl -f http://localhost:8000/employees

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: |
            asrawat130/my-fastapi-app:v6
            asrawat130/my-fastapi-app:latest

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: "projects/19340905514/locations/global/workloadIdentityPools/github-actions/providers/github"
          service_account: "github-cloudrun-deployer@docker-learning-505907.iam.gserviceaccount.com"

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v3
        with:
          service: fastapi-docker-learning
          region: asia-south1
          image: docker.io/asrawat130/my-fastapi-app:v6

      - name: Verify Cloud Run deployment
        run: |
          curl -f "${{ steps.deploy.outputs.url }}/health"

      - name: Stop test environment
        if: always()
        run: |
          docker compose down